In [1]:
open_ai_key = "<YOUR OPEN AI KEY HERE>"

In [2]:
import pandas as pd

# Here we use the PII-98 dataset as an example. But you can use any other dataset such as SVAMP-49 or TriviaQA-114.
pii_98_dataset = pd.read_csv("PII-98-benchmark/pii_98_dataset.csv")
pii_98_dataset.head()

                                              prompt ground_truth
0  Your task is to extract first name from the te...         Tala
1  Your task is to extract first name from the te...  Not present
2  Your task is to extract first name from the te...  Not present
3  Your task is to extract first name from the te...  Not present
4  Your task is to extract first name from the te...      Norbert

In [3]:
from openai import OpenAI

client = OpenAI(api_key=open_ai_key)

responses = []
# Only use the first 5 rows for illustration. Feel free to use the entire dataset.
for _, row in pii_98_dataset.head().iterrows():
    prompt = row['prompt']
    response = client.chat.completions.create(
        messages=[{"role": "user", "content": prompt}],
        model="o1-preview",
    )
    response_text = response.choices[0].message.content
    responses.append(response_text)
    print(f"Prompt: {prompt}")
    print(f"Response: {response_text}")
    print(f"Ground Truth: {row['ground_truth']}")
    print("---")

# Create a new DataFrame with the responses
results_df = pd.DataFrame({
    'prompt': pii_98_dataset.head()['prompt'],
    'ground_truth': pii_98_dataset.head()['ground_truth'],
    'response_openai_o1_preview': responses
})

results_df.to_csv("PII-98-benchmark/pii_98_openai_o1_preview_responses_new.csv", index=False)

# Display the results
results_df

Prompt: Your task is to extract first name from the text.
Please return only the first name as your answer and nothing else.
If there is no first name mentioned in the text, return 'Not Present'

Text:
Dear valued patient, keep in mind that your Eating Disorder therapy session has been scheduled at 12. The therapy cost Tala 964480 is to be paid via mastercard card and confirmed via 73-675301-103047-0 number.
Answer:
Response: Not Present
Ground Truth: Tala
---
Prompt: Your task is to extract first name from the text.
Please return only the first name as your answer and nothing else.
If there is no first name mentioned in the text, return 'Not Present'

Text:
Vaccine appointment slot can now be reserved by sending an SMS to 6500 126 2399. Quote your SSN number 433 47 8265 as a reference.
Answer:
Response: Not Present
Ground Truth: Not present
---
Prompt: Your task is to extract first name from the text.
Please return only the first name as your answer and nothing else.
If there is no first name mentioned in the text, return 'Not Present'

Text:
ICU team. Our contact for late-night deliveries is now 83-391083-420532-3. Call when you see the UUG8X414G1ES30559 from our supplier.
Answer:
Response: Not Present
Ground Truth: Not present
---
Prompt: Your task is to extract first name from the text.
Please return only the first name as your answer and nothing else.
If there is no first name mentioned in the text, return 'Not Present'

Text:
Your course fee payment receipt is attached. A charge of ISK 342,754.57 has been successfully transacted from your credit card 3534282572218237. Halvorson Inc thanks you for choosing to invest in lifelong learning.
Answer:
Response: Not Present
Ground Truth: Not present
---
Prompt: Your task is to extract first name from the text.
Please return only the first name as your answer and nothing else.
If there is no first name mentioned in the text, return 'Not Present'

Text:
Dear Norbert, welcome onboard. For your vehicle, the Parking space number is next to VIN 05BHMWB78RK026069.
Answer:
Response: Norbert
Ground Truth: Norbert
---

,prompt,ground_truth,response_openai_o1_preview
0,Your task is to extract first name from the te...,Tala,Not Present
1,Your task is to extract first name from the te...,Not present,Not Present
2,Your task is to extract first name from the te...,Not present,Not Present
3,Your task is to extract first name from the te...,Not present,Not Present
4,Your task is to extract first name from the te...,Norbert,Norbert