In [ ]:
%pip install --upgrade cleanlab-studio

In [3]:
from cleanlab_studio import Studio

studio = Studio("<your-api-key>")

In [8]:
import pandas as pd

# Here we use the SVAMP-49 dataset as an example. But you can use any other dataset such as PII-98 or TriviaQA-114.
svamp_49_dataset = pd.read_csv("SVAMP-49-benchmark/svamp_49_dataset.csv")
svamp_49_dataset.head()

                                              prompt  ground_truth
0  Matthew gave equal numbers of crackers and cak...             1
1  Jack received 6 emails in the morning, 3 email...             3
2  After eating a hearty meal they went to see th...           949
3  Mary is baking a cake. The recipe calls for 11...             2
4  Last week Fred had 111 dollars and Jason had 4...             4

In [9]:
tlm = studio.TLM(options={"model": "o1-preview"}, quality_preset="best")

responses = []
trustworthiness_scores = []
# Only use the first 5 rows for illustration. Feel free to use the entire dataset.
for _, row in svamp_49_dataset.head().iterrows():
    prompt = row['prompt']
    response_dict = tlm.prompt(prompt)
    responses.append(response_dict['response'])
    trustworthiness_scores.append(response_dict['trustworthiness_score'])
    print(f"Prompt: {prompt}")
    print(f"Response: {response_dict['response']}")
    print(f"Trustworthiness Score: {response_dict['trustworthiness_score']}")
    print(f"Ground Truth: {row['ground_truth']}")
    print("---")

# Create a new DataFrame with the responses and trustworthiness scores
results_df = pd.DataFrame({
    'prompt': svamp_49_dataset.head()['prompt'],
    'ground_truth': svamp_49_dataset.head()['ground_truth'],
    'response_tlm_o1_preview': responses,
    'trustworthiness_score': trustworthiness_scores
})

results_df.to_csv("SVAMP-49-benchmark/svamp_49_tlm_o1_preview_responses_new.csv", index=False)

# Display the results
results_df

Prompt: Matthew gave equal numbers of crackers and cakes to his 28 friends. If he had 13 crackers and 15 cakes initially How many crackers and cakes did each person eat?
Therefore, the answer (arabic numerals) is:
Response: Each friend ate \(\frac{13}{28}\) crackers and \(\frac{15}{28}\) cakes.

So, the answer is: 13⁄28 crackers and 15⁄28 cakes.

**Answer:** 13⁄28 crackers and 15⁄28 cakes.
Trustworthiness Score: 0.9509885426396171
Ground Truth: 1
---
Prompt: Jack received 6 emails in the morning, 3 emails in the afternoon and some more in the evening. If he received a total of 10 emails in the day How many emails did Jack receive in the afternoon?
Therefore, the answer (arabic numerals) is:
Response: To determine how many emails Jack received in the afternoon:

1. **Total emails received in the day**: 10
2. **Emails received in the morning**: 6
3. **Emails received in the afternoon**: 3
4. **Emails received in the evening**: Let's denote this as \( x \)

We can set up the equation:

\[
\text{Morning emails} + \text{Afternoon emails} + \text{Evening emails} = \text{Total emails}
\]

Plugging in the known values:

\[
6 + 3 + x = 10
\]

Solving for \( x \):

\[
9 + x = 10 \\
x = 10 - 9 \\
x = 1
\]

So, Jack received **1 email in the evening**.

However, the question asks: **"How many emails did Jack receive in the afternoon?"**

Based on the information provided:

**Answer:** **3**
Trustworthiness Score: 0.826780596200133
Ground Truth: 3
---
Prompt: After eating a hearty meal they went to see the Buckingham palace. There, Rachel learned that 703 visitors came to the Buckingham palace on the previous day. If there were 246 visitors on that day How many visited the Buckingham palace within 25 days?
Therefore, the answer (arabic numerals) is:
Response: To determine the total number of visitors to Buckingham Palace within 25 days, we'll calculate the average daily visitors based on the two given days and then multiply by 25.

**Given:**
- Visitors on the previous day: 703
- Visitors on the day Rachel visited: 246

**Step 1: Calculate the average number of visitors per day over the two days.**

\[
\text{Average visitors per day} = \frac{703 + 246}{2} = \frac{949}{2} = 474.5
\]

**Step 2: Multiply the average daily visitors by 25 to find the total visitors over 25 days.**

\[
\text{Total visitors in 25 days} = 474.5 \times 25 = 11,862.5
\]

Since we can't have half a visitor, we'll round to the nearest whole number.

**Answer:**

11863
Trustworthiness Score: 0.8476286883275025
Ground Truth: 949
---
Prompt: Mary is baking a cake. The recipe calls for 11 cups of flour and 7 cups of sugar. She already put in some cups of flour. If she still needs 2 more cups of flour than sugar How many cups of flour did she put in?
Therefore, the answer (arabic numerals) is:
Response: To find out how many cups of flour Mary has already put in, let's analyze the information:

- The recipe calls for **11 cups of flour** and **7 cups of sugar**.
- She has already added some cups of flour.
- She still needs **2 more cups of flour than sugar**.

Assuming Mary hasn't added any sugar yet, the amount of sugar she still needs is **7 cups**.

Let \( F \) be the amount of flour she has already added. Then, the amount of flour she still needs is \( 11 - F \) cups.

According to the problem, the amount of flour she still needs is **2 more cups than the sugar**:

\[
11 - F = 7 + 2
\]

Simplify:

\[
11 - F = 9
\]

Subtract 11 from both sides:

\[
- F = -2
\]

Multiply both sides by -1:

\[
F = 2
\]

So, Mary has already put in **2 cups of flour**.

**Answer: 2**
Trustworthiness Score: 0.7999592987447975
Ground Truth: 2
---
Prompt: Last week Fred had 111 dollars and Jason had 40 dollars. Fred washed cars over the weekend and now has 115 dollars. Jason delivered newspapers and now has 44 dollars. How much money did they earn by washing cars?
Therefore, the answer (arabic numerals) is:
Response: 4
Trustworthiness Score: 0.8981307930188448
Ground Truth: 4
---

,prompt,ground_truth,response_tlm_o1_preview,trustworthiness_score
0,Matthew gave equal numbers of crackers and cak...,1,Each friend ate \(\frac{13}{28}\) crackers and...,0.950989
1,"Jack received 6 emails in the morning, 3 email...",3,To determine how many emails Jack received in ...,0.826781
2,After eating a hearty meal they went to see th...,949,To determine the total number of visitors to B...,0.847629
3,Mary is baking a cake. The recipe calls for 11...,2,To find out how many cups of flour Mary has al...,0.799959
4,Last week Fred had 111 dollars and Jason had 4...,4,4,0.898131

# Try individual examples

In [3]:
tlm = studio.TLM(options={"model": "o1-preview", "cache_enabled": False}, quality_preset="best")

prompt = """Zachary did 53 push-ups and 14 crunches in gym class today. David did 17 more push-ups but 10 less crunches than zachary. How many push-ups and crunches did Zachary do?
Therefore, the answer (arabic numerals) is: 
"""
import json
print(json.dumps(tlm.prompt(prompt), indent=4))

{
    "response": "Zachary did 53 push-ups and 14 crunches.",
    "trustworthiness_score": 0.6936745208231877
}